---
sidebar: sidebar 
permalink: use/task-monitor-operations.html 
keywords: monitor jobs, track jobs, monitor, track, NetApp Console, bluexp 
summary: 使用NetApp Console中的 Tracker 跟踪 FSx for ONTAP操作并监控操作进度。 
---
= 使用NetApp Console中的 Tracker 监控 FSx for ONTAP操作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
监控和跟踪 FSx for ONTAP操作的执行情况，并使用NetApp Console中的 Tracker 监控作业进度。

.关于此任务
NetApp Console提供了 Tracker（一项作业监控功能），因此您可以监控和跟踪凭证、FSx for ONTAP和链接操作的进度和状态，查看操作任务和子任务的详细信息，并诊断任何问题或故障。

Tracker 中提供了多种操作。您可以按时间范围（过去 24 小时、7 天、14 天或 30 天）、工作量、状态和用户筛选作业；使用搜索功能查找作业；并将作业表下载为 CSV 文件。您可以随时刷新追踪器。您可以快速重试失败的操作或编辑失败操作的参数并再次尝试该操作。

Tracker 根据操作支持两种级别的监控。每个任务（例如文件系统部署）显示任务描述、状态、开始时间、任务持续时间、用户、区域、代理资源、任务 ID 以及所有相关子任务。您可以查看 API 响应以了解操作期间发生的情况。

带有示例的跟踪器任务级别::
+
--
* 级别 1（父任务）：跟踪文件系统部署。
* 第 2 级（子任务）：跟踪与文件系统部署相关的子任务。


--
运行状态:: Tracker 中的操作状态如下：_进行中_、_成功_和_失败_。
操作频率:: 操作频率取决于任务类型和时间表。
事件保留:: 事件在用户界面中保留 30 天。




== 跟踪和监控操作

使用 Tracker 跟踪和监控NetApp Console中的操作。

.步骤
. 从NetApp Console菜单中，选择 *Workloads*，然后选择 *Administration*。
. 从管理菜单中，选择*跟踪器*。
. 在跟踪器中，查看任务或使用过滤器或搜索来缩小结果范围。您还可以通过选择*导出 CSV*来下载所有操作的报告。




== 查看 API 请求

在 Codebox 中查看 Tracker 中任务的 API 请求。

.步骤
. 在 Tracker 中，选择一个任务。
. 选择三点菜单，然后选择*查看 API 请求*。




== 重试失败的操作

在 Tracker 中重试失败的操作。重试失败的操作将启动一个新任务，您可以在 Tracker 中监控该任务。

您还可以复制操作失败的错误消息。


NOTE: 您只能重试一次失败的操作。

.步骤
. 在 Tracker 中，选择一个失败的操作。
. 选择三点菜单，然后选择*重试*。


.结果
该操作重新启动并作为新任务出现在 Tracker 中。



== 编辑并重试失败的操作

编辑失败操作的参数并在 Tracker 之外重试该操作。

.步骤
. 在 Tracker 中，选择一个失败的操作。
. 选择三点菜单，然后选择*编辑并重试*。
+
您将被重定向到操作页面，例如卷创建，您可以在其中编辑参数并重试操作。



.结果
操作已重新启动。前往 Tracker 查看操作状态。
