---
sidebar: sidebar 
permalink: use/task-replicate-data.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, bluexp, NetApp Console 
summary: 在NetApp Console中创建或发现 FSx for ONTAP系统后，您可以管理文件系统并使用提供备份和恢复等功能的NetApp数据服务。 
---
= 在 NetApp Console 中复制 FSx for ONTAP 数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
复制数据以防止数据丢失，如果数据所在的区域发生灾难。FSx for ONTAP 文件系统与本地 ONTAP 系统或 Cloud Volumes ONTAP 之间支持数据复制。

.关于此任务
此操作为 FSx for ONTAP 文件系统、本地 ONTAP 系统或 Cloud Volumes ONTAP 系统中的源卷创建复制关系。

目标文件系统中的复制卷是数据保护 (DP) 卷，并遵循以下命名格式： `{OriginalVolumeName}_copy`。

.开始之前
在开始之前请考虑以下事项。

* 若要在 FSx for ONTAP 和本地 ONTAP 或 Cloud Volumes ONTAP 之间复制数据，您必须选择一个连接到文件系统的 Console 代理，或输入文件系统以关联链接。link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["了解如何使用链接"^]
* 不支持对处于可用、已创建或配置错误以外的状态以及 ONTAP 版本不兼容的卷执行复制。


.步骤
. 从 NetApp Console 系统页面，将源 FSx for ONTAP 文件系统、本地 ONTAP 系统或 Cloud Volumes ONTAP 系统拖到目标 FSx for ONTAP 文件系统之上，然后选择*复制*。
. 在“创建复制”页面上，选择要复制的源卷，然后单击“下一步”。
. 在复制目标下，提供以下内容：
+
.. *目标名称*：在 Console Systems 页面中将源存储系统拖放到目标系统上时应用了目标名称。
.. *用例*：选择以下其中一个用例进行复制。根据所选的用例，Workload Factory 会根据最佳实践在表单中填写推荐值。您可以接受建议的值，也可以在填写表格时进行更改。
+
*** 迁移：将您的数据传输到目标 FSx for ONTAP文件系统
*** 热灾难恢复：确保关键工作负载的高可用性和快速灾难恢复
*** 冷灾难恢复或存档灾难恢复：
+
**** 冷灾难恢复：使用更长的恢复时间目标（RTO）和恢复点对象（RPO）来降低成本
**** 存档：复制数据以实现长期存储和合规性


*** 其他
+
此外，用例选择决定了复制策略或SnapMirror策略（ONTAP）。用于描述复制策略的术语来自link:https://docs.netapp.com/us-en/ontap/data-protection/default-protection-policies-concept.html["ONTAP 9 文档"^]。

+
**** 对于迁移和其他，复制策略称为_MirrorAllSnapshots_。  _MirrorAllSnapshots_ 是一种异步策略，用于镜像所有快照和最新的活动文件系统。
**** 对于热、冷或存档灾难恢复，复制策略称为_MirrorAndVault_。  _MirrorAndVault_ 是一种异步和保险库策略，用于镜像最新的活动文件系统以及每日和每周快照。
+
对于所有用例，如果您启用快照进行长期保留，则默认复制策略为_MirrorAndVault_。





.. *FSx for ONTAP 文件系统*：为目标 FSx for ONTAP 文件系统选择凭据、区域和 FSx for ONTAP 文件系统名称。
.. *存储虚拟机名称*：从下拉菜单中选择存储虚拟机。您选择的存储虚拟机是此复制关系中所有选定卷的目标。
.. *卷名称*：目标卷名称自动生成，格式如下 `{OriginalVolumeName}_copy`。您可以使用自动生成的卷名或输入其他卷名。
.. *分层策略*：选择目标卷中存储的数据的分层策略。分层策略默认为您选择的用例的推荐分层策略。
+
使用 Workload Factory 控制台创建卷时，_平衡（自动）_ 是默认分层策略。有关卷分层策略的更多信息，请参阅link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["卷存储容量"^]在 AWS FSx for NetApp ONTAP文档中。请注意，工作负载工厂在工作负载工厂控制台中使用基于用例的名称来制定分层策略，并在括号中包含 FSx for ONTAP分层策略名称。

+
如果您选择了迁移用例，Workload Factory 会自动选择将源卷的分层策略复制到目标卷。您可以取消选择复制分层策略并选择适用于选择进行复制的卷的分层策略。

.. *最大传输速率*：选择*限制*并输入最大传输限制（MB/s）。或者，选择*无限制*。
+
如果没有限制，网络和应用程序性能可能会下降。或者，我们建议对于关键工作负载（例如主要用于灾难恢复的工作负载）使用 FSx for ONTAP文件系统的无限制传输速率。



. 在复制设置下，提供以下内容：
+
.. *复制间隔*：选择快照从源卷传输到目标卷的频率。
.. *长期保留*：可选地，启用快照以进行长期保留。长期保留使业务服务即使在整个站点发生故障时也能继续运行，支持应用程序使用辅助副本透明地进行故障转移。
+
没有长期保留的复制使用_MirrorAllSnapshots_策略。启用长期保留会将 _MirrorAndVault_ 策略分配给复制。

+
如果启用长期保留，则选择现有策略或创建新策略来定义要复制的快照和要保留的数量。

+

NOTE: 长期保留需要匹配的源标签和目标标签。如果需要，工作负载工厂可以为您创建缺失的标签。

+
*** *选择现有策略*：从下拉菜单中选择一个现有策略。
*** *创建新策略*：输入*策略名称*。


.. *不可变快照*：可选。选择“启用不可变快照”以防止在保留期内删除此策略中拍摄的快照。
+
*** 以小时、天、月或年为单位设置*保留期*。
*** *快照策略*：在表格中，选择快照策略频率和要保留的副本数。您可以选择多个快照策略。


.. *S3 access point*：可选择连接 S3 access point，通过 AWS S3 API 访问驻留在 NFS 或 SMB/CIFS 卷上的 FSx for ONTAP 文件系统数据。仅支持文件访问类型。提供以下详细信息：
+
*** *S3 接入点名称*：输入 S3 接入点的名称。
*** *User*：选择有权访问卷的现有用户或创建新用户。
*** *用户类型*：选择 *UNIX* 或 *Windows* 作为用户类型。
*** *网络配置*：选择 *Internet* 或 *Virtual private cloud (VPC)*。您选择的网络类型决定了接入点是可从互联网访问还是仅限于特定的 VPC。
*** *启用元数据*：启用元数据会创建一个 S3 表，其中包含 S3 访问点可访问的所有对象，可用于审计、治理、自动、分析和优化。启用元数据会产生额外的 AWS 成本。有关详细信息，请参见 link:https://aws.amazon.com/s3/pricing/["Amazon S3 定价文档"^]。


.. *S3 接入点标签*：您最多可以添加 50 个标签（可选）。




. 选择“*创建*”。

