---
sidebar: sidebar 
permalink: use/task-manage-fsx-systems.html 
keywords: amazon fsx for netapp ontap, fsx, manage fsx for ontap system, delete fsx for ontap system, remove fsx for ontap system, throughput capacity, change throughput, automatic capacity management, capacity management, storage capacity, replication, classification, sync, backup, recovery, bluexp, NetApp Console 
summary: 在NetApp Console中创建或发现 FSx for ONTAP系统后，您可以管理文件系统并使用提供备份和恢复等功能的NetApp数据服务。 
---
= 在NetApp Console中管理 FSx for ONTAP文件系统
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
在NetApp Console中创建或发现 FSx for ONTAP系统后，您可以通过创建卷、管理存储虚拟机、保护数据和管理文件系统来管理文件系统。控制台还使您能够使用提供备份和恢复、数据分类、数据同步等功能的数据服务。



== 使用NetApp Workloads 管理文件系统

当您从 NetApp Console 系统页面打开 FSx for ONTAP 系统时，您将进入 NetApp Workloads。Workloads 是一种智能优化和自动化服务，它使用行业最佳实践来规划、配置和操作使用 Amazon FSx for NetApp ONTAP 的关键工作负载。

https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["了解如何使用NetApp Workloads 管理文件系统"^]



== 使用ONTAP系统管理器管理文件系统

您可以使用ONTAP系统管理器界面直接从控制台管理 FSx for ONTAP文件系统。使用系统管理器需要控制台代理或 AWS Lambda 链接。

link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["了解如何使用链接"^]



== 使用 Amazon CloudFormation 管理文件系统

您可以使用 Amazon CloudFormation 配置和管理 FSx for ONTAP文件系统资源（卷、CIFS 共享、导出策略等）。

link:https://github.com/NetApp/NetApp-CloudFormation-FSx-ONTAP-provider["NetApp CloudFormation FSx for ONTAP提供商 GitHub 存储库"^]



== 将NetApp数据服务与文件系统结合使用

将NetApp数据服务与您的 FSx for ONTAP文件系统结合使用，以备份和恢复数据、传输和同步数据、扫描和分类数据、复制数据以及加快访问或卸载流量。



=== 备份和恢复您的数据

NetApp Backup and Recovery为本地和云端的NetApp ONTAP数据、数据库和虚拟机提供高效、安全且经济的数据保护。

link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["开始使用NetApp Backup and Recovery"^]



=== 传输和同步数据

NetApp Copy and Sync是一种云复制和同步服务，用于在本地和云对象存储之间传输 NAS 数据。

link:https://docs.netapp.com/us-en/data-services-copy-sync/task-quick-start.html["开始使用NetApp Copy and Sync"^]



=== 扫描并分类您的数据

NetApp Data Classification使您能够扫描和分类组织混合多云中的数据。

link:https://docs.netapp.com/us-en/data-services-data-classification/index.html["开始使用NetApp Data Classification"^]



=== 加快访问速度或卸载流量

NetApp Volume Caching在远程位置提供持久、可写的卷。您可以使用卷缓存来加快数据访问速度或卸载访问频繁的卷的流量。

link:https://docs.netapp.com/us-en/console-volume-caching/get-started/cache-intro.html["开始使用NetApp Volume Caching"^]
