---
sidebar: sidebar 
permalink: start/concept-fsx-aws.html 
keywords: Amazon FSx for NetApp ONTAP, volumes, aws, access key, secret key, cloud manager, NetApp Console, bluexp 
summary: Amazon FSx for NetApp ONTAP是一项完全托管的服务，允许客户启动和运行由 NetApp 的ONTAP存储操作系统提供支持的文件系统。 
---
= 了解适用Amazon FSx for NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSx for NetApp ONTAP"^]是一项完全托管的服务，允许客户启动和运行由NetApp ONTAP存储操作系统提供支持的文件系统。  FSx for ONTAP提供NetApp客户在本地使用的相同功能、性能和管理功能，同时具有原生 AWS 服务的简单性、灵活性、安全性和可扩展性。



== NetApp Console

可通过NetApp Console访问Amazon FSx for NetApp ONTAP管理。

NetApp Console提供企业级跨本地和云环境的NetApp存储和数据服务的集中管理。需要控制台才能访问和使用NetApp数据服务。作为管理界面，它使您能够从一个界面管理许多存储资源。控制台管理员可以控制企业内所有系统的存储和服务的访问。

您不需要许可证或订阅即可开始使用NetApp Console，并且只有当您需要在云中部署控制台代理以确保与存储系统或NetApp数据服务的连接时才需要付费。但是，一些可从控制台访问的NetApp数据服务是需要许可或基于订阅的。

详细了解 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["NetApp Console"]。



== 从NetApp Console使用 FSx for ONTAP

在NetApp Console系统页面，您可以创建和发现 FSx for ONTAP系统并使用系统管理器和其他NetApp服务。如果您要管理 FSx for ONTAP系统和在Amazon FSx for NetApp ONTAP上运行的工作负载，请使用 https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["NetApp Workload Factory"^]。

link:../use/task-create-fsx-system.html["了解如何从NetApp Console创建和发现 FSx for ONTAP系统"]。



== 功能

* 无需配置或管理存储设备、软件或备份。
* 支持 CIFS、iSCSI、NFSv3、NFSv4.x、 https://docs.netapp.com/us-en/ontap/s3-config/ontap-version-support-s3-concept.html["S3"^]以及 SMB v2.0 - v3.1.1 协议。
* 使用可用的不频繁访问 (IA) 存储层，实现低成本、几乎无限的数据存储容量。
* 经过认证，可在包括 Oracle RAC 在内的延迟敏感应用程序上运行。
* 选择捆绑和现收现付定价。




== NetApp Console中的其他功能

* 在标准模式下使用NetApp Console时支持 FSx for ONTAP ，它利用NetApp Console SaaS 层提供完整功能。不支持_Restricted_模式和_private_模式。


请参阅link:https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["NetApp Console部署模式"^]了解更多信息。

* 使用link:https://docs.netapp.com/us-en/console-family/["NetApp Console"^]以及 AWS 中的控制台代理，您可以创建和管理卷、复制数据以及将 FSx for ONTAP与NetApp云服务（例如NetApp Data Classification和NetApp Copy and Sync）集成。
* NetApp Data Classification使用人工智能 (AI) 驱动的技术，可以帮助您了解数据上下文并识别驻留在 FSx for ONTAP帐户中的敏感数据。 https://docs.netapp.com/us-en/data-services-data-classification/concept-cloud-compliance.html["了解更多"^] 。
* 使用NetApp Copy and Sync，您可以自动将数据迁移到云端或本地的任何目标。 https://docs.netapp.com/us-en/data-services-copy-sync/concept-cloud-sync.html["了解更多"^]




== 控制台代理和链接解锁所有 FSx for ONTAP功能

控制台代理和链接支持NetApp Console和Amazon FSx for NetApp ONTAP工作环境之间的连接和信任关系。控制台代理是在您的云或本地网络中运行的NetApp软件，并且链接使用 AWS Lambda 执行NetApp代码。您不需要控制台代理或链接即可在控制台中开始或创建 FSx for ONTAP系统，但您需要使用控制台代理或链接才能充分利用 FSx for ONTAP功能。

您需要控制台代理或链接才能使用以下功能：

* FSx for ONTAP文件系统配置的良好架构状态，可实现主动维护、可靠性和成本效益优化
* NetApp自主勒索软件防护 (ARP/AI)
* 增强了 FSx for ONTAP文件系统的整体容量可观察性
* 卷和存储虚拟机数据复制、管理和监控
* SMB/CIFS 共享和 NFS 导出策略配置和管理
* FSx for ONTAP文件系统上的 iSCSI 卷管理
* 创建和管理自定义保护 SLA 的快照策略
* 增强 Inode 管理以实现自动容量管理
* 容量自动增长以实现弹性扩展
* 克隆创建和管理，用于即时、就地数据克隆
* 直接从ONTAP显示其他指标，例如ONTAP版本


了解有关控制台代理和链接的更多信息以及何时使用它们：

* https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["了解有关控制台代理的更多信息"^] 。
* https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["了解有关链接的更多信息"^] 。




== 成本

您的 FSx for ONTAP帐户由 AWS 维护，而不是由NetApp维护。参考 https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSx for NetApp ONTAP入门指南"^]。

使用 AWS 中的控制台代理或链接以及可选数据服务（例如NetApp Data Classification和NetApp Copy and Sync）会产生额外费用。



== 支持的区域

https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["查看支持的亚马逊区域。"^]



== 获取帮助

Amazon FSx for NetApp ONTAP是 AWS 第一方解决方案。如果您对 FSx for ONTAP文件系统、基础设施或任何使用此服务的解决方案有疑问或技术支持问题，请使用 AWS 管理控制台中的支持中心向 AWS 提交支持案例。选择“FSx for ONTAP”服务和适当的类别。提供创建 AWS 支持案例所需的其余信息。

对于特定于NetApp Console或NetApp存储解决方案和服务的一般和技术支持问题，您可以使用NetApp组织级序列号打开NetApp支持票证。你需要link:https://docs.netapp.com/us-en/storage-management-fsx-ontap/support/task-support-registration.html["注册您的NetApp组织"^]激活支持。
